# (C) Copyright 2023 Hewlett Packard Enterprise Development LP

name: go lint
description: runs golangci-lint

runs:
  using: "composite"
  steps:

  - name: golangci-lint
    id: golint
    uses: golangci/golangci-lint-action@v3
