# (C) Copyright 2023 Hewlett Packard Enterprise Development LP

name: tag manage
description: |
  N.B. You must pull the repo with fetch-depth: 0 to get all tags.



runs:
  using: "composite"
  steps:

    - name: setup tag-manage
      shell: bash
      run: |

        echo "fetching tag-manage from containers repo"

