name: reusable CI

on:
  workflow_call:
    inputs:
    #   java-version:
    #     required: true
    #     type: number
      repository:
        required: false
        description: The repository to checkout. Should only be used for verifying changes to the workflow itself.
        type: string
        default: ${{ github.repository }}
    secrets:
      SSH_KEY:
        required: false
        description: The SSH key to use for checking out the repository. Should only be used for verifying changes to the workflow itself.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 1
         repository: ${{ inputs.repository }}
         ssh-key: ${{ secrets.SSH_KEY }}
      - run: ls -la
      - name: setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'


      - uses: sivahpe/action-reuse/.github/actions/tag-manage@main
      
      - name: unit tests
        id: unit-test
        uses: sivahpe/action-reuse/.github/actions/go-unit@main
        with:
          directories-to-test: ./hello-world
